const constants = require('../constants')
const express = require('express'),
      Router = express.Router(),
      utils = require('utility'),
      User = require('../models')('User')

Router.get('/info', (req, res) => {
    console.log('info called')
    const {_id, pwd} = req.cookies
    if(!_id){
        return res.json({
            code:constants.NO_COOKIE
        })
    }
    User.findOne({_id, password:pwd}, (err, user)=>{
        if(err){
            return res.json({
                code:constants.AUTH_FAILURE
            })
        }
        if(user){
            return res.json({
                code:constants.AUTH_SUCCESS,
                userInfo:user
            })
        }
    })
})
Router.post('/login', (req, res) => {
    const {user, pwd} = req.body
    // using _filter is because we don't want password to be exposed when finding users
    User.findOne({user, pwd:md5Pwd(pwd)}), _filter, (err, doc)=>{
        if(!doc){
            return res.json({code: 1, msg: 'the user does not exist or password is wrong'})
        }else{
            // normally we should use the doc._id which is GUID generated by mongodb,
            // this id can uniquely identify the user
            res.cookie('userId', doc._id)
            return res.json({code: 0, data: doc})
        }
    }
})
Router.post('/register', (req, res) => {
    const {userName, password, email} = req.body
    console.log(userName)
    User.findOne({userName}, (err, doc) => {
        if(doc){
            return res.json({code: 1, msg:'username is already existing'})
        }
        const userModel = new User({userName, password, email})
        userModel.save((err, doc)=>{
            if(err){
                return res.json({code: 1, msg:'error happened in backend'})
            }
            console.log('sver succ')
        })
        // you cannot use User.create method as it cannot achieve user's id,
        // there exist ids only after users are created
        // User.create({user, pwd:md5Pwd(pwd), type}, (err, doc) => {
        //     if(err){
        //         return res.json({code: 1, msg:'error happened in backend'})
        //     }
        //     return res.json({code: 0})
        // })
    })
})

module.exports = Router

function md5Pwd(pwd){
    const salt = 'Chris_can_code_skf@%*jk3&SJF~'
    return utils.md5(utils.md5(pwd + salt))
}